import type { Metadata } from 'next';

const MetaResolve: Metadata = {
  title: 'Create Next App',
  authors: [
    {
      name: 'chase ottofy',
      url: 'https://ottofy.dev',
    },
  ],
  creator: 'chase ottofy',
  keywords: 'ottofy, chaseottofy, react, nextjs',
  description: 'Generated by create next app',
  icons: [
    {
      rel: 'icon',
      type: 'image/svg+xml',
      sizes: 'any',
      url: '/icon.svg',
    },
  ],
};

export default MetaResolve;
