import type { Metadata } from 'next';

export const authors: Metadata['authors'] = [
  {
    name: 'chase ottofy',
    url: 'https://ottofy.dev',
  },
];

export const creator: Metadata['creator'] = 'chase ottofy';

export const keywords: Metadata['keywords'] = 'ottofy, chaseottofy, react, nextjs';

export const description: Metadata['description'] = 'Generated by create next app';

export const icons: Metadata['icons'] = [
  {
    rel: 'icon',
    type: 'image/svg+xml',
    sizes: 'any',
    url: '/favicon.svg',
  },
];

// const MetaResolve: Metadata = {
//   title: 'next app',
//   authors: [
//     {
//       name: 'chase ottofy',
//       url: 'https://ottofy.dev',
//     },
//   ],
//   creator: 'chase ottofy',
//   keywords: 'ottofy, chaseottofy, react, nextjs',
//   description: 'Generated by create next app',
//   icons: [
//     {
//       rel: 'icon',
//       type: 'image/svg+xml',
//       sizes: 'any',
//       url: '/favicon.svg',
//     },
//   ],
// };

// export default MetaResolve;
